import "./globals.css";
import type { Metadata } from "next";
import { Commissioner } from "next/font/google";
import { Sidebar } from "@/components/common/sidebar/Sidebar";
import Providers from "@/providers";

const commissioner = Commissioner({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-Commissioner",
});

export const metadata: Metadata = {
  title: "slate-web-next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${commissioner.variable} font-sans`}>
        <div className="flex">
          <Providers>
            <Sidebar />
            <div className="overflow-hidden">{children}</div>
          </Providers>
        </div>
      </body>
    </html>
  );
}
